### ISSUE TITLE
IHandlerResolver should support releasing handlers

### ISSUE THREAD

**Issue by codedemonuk** [justeat/JustSaying#206]
IHandlerResolver has no method to allow the resolved handler to be released.  This can cause memory leaks in IoC containers such as Ninject, Windsor where you need to release components.

Would it be possible to add a release method to the IHandlerResolver and use that to allow handlers to be explicitly released by their IoC containers when people implement their own IHandlerResolvers.

**Comment by payman81** [comment]
Why don't you implement IDisposable in your handlers and let your IoC container release them when they're out of scope?
Can you share your implementation of IHandlerResolver or send me a gist that shows the memory leak?
Implementation of IHandlerResolver isn't meant to hold reference to any IDisposable. It should simply pass the call to the IoC container. Here is an implementation for StructureMap:
````
public class StructureMapHandlerResolver : IHandlerResolver
{
    private readonly IContainer _container;

    public StructureMapHandlerResolver(IContainer container)
    {
        _container = container;
    }

    public IEnumerable<IHandler<T>> ResolveHandlers<T>()
    {
        return _container.GetAllInstances<IHandler<T>>();
    }
}
````

**Comment by codedemonuk** [comment]
The issue is not a defect in JustSaying.

A number of IoC containers such as Castle Windsor keep track of all of the components that have been resolved (including transient objects) and the container will not release it's reference to these components until the container's `Release` method has been called.

This results in a memory leak because the CLR garbage collection will not collect these transient objects because Windsor will always have a reference to the object.

More details about this behaviour are in the [Castle Windsor documentation][1] 

Other frameworks like Quartz accommodate this behaviour in IoC frameworks by including a method on their interfaces to allow a resolved component to be released - [an example of how Quartz handles it][2].

[1]: https://github.com/castleproject/Windsor/blob/master/docs/release-policy.md
[2]: https://github.com/quartznet/quartznet/blob/b03aa020168a63ab062cb703804e845a07c2003f/src/Quartz/SPI/IJobFactory.cs

**Comment by AnthonySteele** [comment]
Just for curiosity, have you observed a memory leak, and how severe is it?

**Comment by stuart-lang** [comment]
I can see how this would be a problem for you. MEF works the same way with regards to holding onto ```IDisposable```, we "fixed" it the time by introducing an ```IClosable``` (someone wanted us to call it ```IDismosable``` lol). You container holding on to this reference will keep your whole object graph alive, not good.

If you depend on disposable dependencies, I would recommend your handlers do not implement IDisposable, but you inject a factory which creates and releases your IDisposable inside of your handle method, giving you control to release it. That being said, adding this to JustSaying would remove this boilerplate for you.

**Comment by payman81** [comment]
For transient scope, you'd want to release when you finish handling every message. But what about per request scope? At what point would you call Release then?

**Comment by stuart-lang** [comment]
@payman81 I'm confused, I thought "Transient Scope" == "Per Request Scope"

**Comment by payman81** [comment]
@stuart-lang I meant something like Ninject's [InRequestScope](https://github.com/ninject/Ninject.Web.Common/wiki/InRequestScope)

**Comment by GraemeF** [comment]
That's fine for a web request, but there's no such scope for a message (although it would make sense imo).

**Comment by codedemonuk** [comment]
I've seen this issue with IoC containers catch out a number of people. The application will work for a few weeks until the server memory fills up and the application crashes.

For the message handlers you would want to release the handler after the message has been processed.

**Comment by jaimalchohan** [comment]
This all seems very leaking-of-concerns for JustSaying (it ain't Castle.JustSaying!)

Why not force the Registation to require a Func<T, bool> and let the client app handle IOC in any way it wants.

E.g.

```
WithMessageHandler<OrderAcceptedMessage>(orderAcceptedMessage => {
  ObjectFactory.GetInstance<OrderAcceptedHandler>().DoTheThing(orderAcceptedMessage)
});

or if I don't use IOC 

WithMessageHandler<OrderAcceptedMessage>(orderAcceptedMessage => {
  new OrderAcceptedHandler().DoTheThing(orderAcceptedMessage)
});

or if my type is thread-safe

WithMessageHandler<OrderAcceptedMessage>(orderAcceptedMessage => {
  _orderAcceptedHandler.DoTheThing(orderAcceptedMessage)
});

or I really like statics

WithMessageHandler<OrderAcceptedMessage>(orderAcceptedMessage => {
  OrderAcceptedHandler.DoTheThing(orderAcceptedMessage)
});

```

**Comment by GraemeF** [comment]
Yep, you could create an IoC scope in there too, if your container supports them and you want to use that to control object lifetimes. Or use `using` statements to dispose of things you create, etc.

**Comment by AnthonySteele** [comment]
After looking at the code - can we confirm that the Handlerresovler should create a new handler each time? This might have been changed accidentally, check history on this line: https://github.com/justeat/JustSaying/blob/master/JustSaying/JustSayingFluently.cs#L254

It might have to go back to being 

````csharp
Bus.AddMessageHandler(region, _subscriptionConfig.QueueName, 
      () => handlerResolver.ResolveHandlers<T>().Single());
````

as it used to be here: https://github.com/justeat/JustSaying/blob/3aee35f286c247ba2739f6ba57ec770a13dc7656/JustSaying/JustSayingFluently.cs#L247

I.e. do the `ResolveHandlers` call inside the fn. 

Note that the other overload, `WithMessageHandler<T>(IHandler<T> handler)` still uses the same handler instance for the lifetime of the app.

**Comment by stuart-lang** [comment]
@jaimalchohan very nice 👍 Essentially the workaround I am describing is to do exactly what you did in your top example, with the ```Handle``` method on the ```IHandler``` instance as the ```Func```. Your suggestion offers better flexibility and simplicity.
@AnthonySteele I would have guessed the handler to be transient if not explicitly configured or documented, we should probably document it in either case.

**Comment by AnthonySteele** [comment]
I would also have guessed the handler to be transient by default, and it looks like it was, but only if you used a `IHandlerResolver`. 

Unfortunately it's not documented or tested, so it changed without anything going immediately wrong. I have put in a quick PR to change it back, pending something more thorough (and potentially breaking)

**Comment by AnthonySteele** [comment]
I think @jaimalchohan 's thinking has merit, but we must also remember that at present that there are two interfaces: `IHandlerAsync` and `IHandler` 

JustSaying could be concerned only with the most general case registering a `Func<IHandlerAsync<T>>` and all the other cases handled by external code and / or helper extension methods that wrap it into the most general one.

**Comment by GraemeF** [comment]
The interfaces are useful when you want to resolve them from a container (i.e. "get me an `IFooReturner`" specifically, rather than the more general "get me a `Func<Foo>`") but I would hope that most folks are writing some code to configure JustSaying rather than using a container to resolve it.

**Comment by AnthonySteele** [comment]
It is easy to replace the `IHandlerResolver` with a function, as it is never resolved from a container. It is the other way around: it forwards handler resolution to the container.

`IHandler` and `IHandlerAsync` are not the same though: they are resolved, unless there is a more fundamental change.

**Comment by codedemonuk** [comment]
Since the IHandlerResolver interface exists as an easy way of wiring in your choice of DI container to JustSaying it would seem logical to use it to resolve your handlers when a message is received.

I like @jaimalchohan's suggestion - but the only down side would be that it would make the registrations very verbose if you are resolving your handlers from a DI container that requires you to release them.

```c#
WithMessageHandler<OrderAcceptedMessage>(orderAcceptedMessage =>
  {
    var handler = ObjectFactory.GetInstance<OrderAcceptedHandler>();
    try 
    {
      handler.DoTheThing(orderAcceptedMessage));
    } 
    finally 
    {
      HandlerFactory.Release(handler);
    }
  });
```

It's not as nice as the current syntax where you can just pass the IHandlerResolver instance and let the framework take care of the rest of the details for you.

**Comment by AnthonySteele** [comment]
@codedemonuk does this PR address some of the issue? https://github.com/justeat/JustSaying/pull/215/files

**Comment by stuart-lang** [comment]
@AnthonySteele I would imagine that PR215 would not improve the situation, because now it is being resolved more than once. If the handlers are registered as singletons then it will have no effect, otherwise it will exacerbate the issue. Still needs a workaround or us to add a release method.

**Comment by codedemonuk** [comment]
I agree with @stuart-lang , the PR still does not allow the handler resolver to dispose of a handler once it has been used.

**Comment by dariusdamalakas** [comment]
@codedemonuk 
>This results in a memory leak because the CLR garbage collection will not collect these transient objects because Windsor will always have a reference to the object.
> <..> the application will work for a few weeks until the server memory fills up and the application crashes.

What we could do nail down the issue and have some proof that this is the issue we could replace the engine to cut out the AWS and start feeding dummy messages, and run this in a loop. Perhaps a test marked as ignored/manual would be best here. We could run this with debugger/profiler attached and quickly see if running this over millions of messages results in increased memory usage.

**Comment by stuart-lang** [comment]
@dariusdamalakas We could use the dotmemory libraries to achieve this:
https://www.jetbrains.com/dotmemory/unit/
However, I honestly do not think it is worth it. We would be confirming known behaviours of external container libraries.
